//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH.Engine.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BH.Engine.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;_t&quot; : &quot;BH.oM.Common.Materials.Material&quot;, &quot;BHoM_Guid&quot; : &quot;5dda9192-003a-4e5d-99da-5c7e7eb3c24b&quot;, &quot;Name&quot; : &quot;S235&quot;, &quot;Tags&quot; : [], &quot;CustomData&quot; : { }, &quot;Type&quot; : 1, &quot;YoungsModulus&quot; : 210000000000.0, &quot;PoissonsRatio&quot; : 0.29999999999999999, &quot;ShearModulus&quot; : 0.0, &quot;DryDensity&quot; : 7850.0, &quot;CoeffThermalExpansion&quot; : 1.17E-05, &quot;DampingRatio&quot; : 0.0, &quot;Density&quot; : 7850.0, &quot;CompressiveYieldStrength&quot; : 235000000.0, &quot;TensileYieldStrength&quot; : 235000000.0, &quot;StainAtYield&quot; : 0.11 }
        ///{ &quot;_t&quot; : &quot;BH.oM.Common.Materials.Material&quot;, &quot;BHoM_G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialsEurope {
            get {
                return ResourceManager.GetString("MaterialsEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;_t&quot; : &quot;BH.oM.Structural.Properties.TubeDimensions&quot;, &quot;BHoM_Guid&quot; : &quot;7a2f38c5-64fb-44d3-9244-71ccfacf0c76&quot;, &quot;Name&quot; : &quot;CHS 21.3x3.2&quot;, &quot;Tags&quot; : [], &quot;CustomData&quot; : { }, &quot;Shape&quot; : 6, &quot;Diameter&quot; : 0.021299999999999999, &quot;Thickness&quot; : 0.0032000000000000002 }
        ///{ &quot;_t&quot; : &quot;BH.oM.Structural.Properties.TubeDimensions&quot;, &quot;BHoM_Guid&quot; : &quot;6d372c5e-866a-40e1-9d6c-d371310b3221&quot;, &quot;Name&quot; : &quot;CHS 26.9x3.2&quot;, &quot;Tags&quot; : [], &quot;CustomData&quot; : { }, &quot;Shape&quot; : 6, &quot;Diameter&quot; : 0.0269, &quot;Thickness&quot; : 0.0032000000000000002 }
        ///{ &quot;_t&quot; : &quot;BH.oM.St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UK_SteelSectionDimensions {
            get {
                return ResourceManager.GetString("UK_SteelSectionDimensions", resourceCulture);
            }
        }
    }
}
