/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

using BH.oM.Geometry;
using BH.oM.Structure.Loads;
using BH.oM.Base;
using BH.oM.Structure.Elements;
using System.Collections.Generic;
using System.Linq;
using System;
using System.ComponentModel;
using BH.oM.Base.Attributes;
using BH.oM.Quantities.Attributes;

namespace BH.Engine.Structure
{
    public static partial class Create
    {
        /***************************************************/
        /**** Public Methods                            ****/
        /***************************************************/

        [PreviousVersion("5.1", "BH.Engine.Adapters.Robot.Create.GeometricalLineLoad(BH.oM.Geometry.Line, BH.oM.Structure.Loads.Loadcase, BH.oM.Geometry.Vector, System.String)")]
        [Description("Creates a GeometricalLineLoad with a constant force across the length of the Line.")]
        [InputFromProperty("location")]
        [InputFromProperty("loadcase")]
        [Input("force", "The force to be applied to the full length of the Line.", typeof(BH.oM.Quantities.Attributes.Force))]
        [Input("name", "The name of the created load.")]
        [Output("geoLineLoad", "The created GeometricalLineLoad.")]
        public static GeometricalLineLoad GeometricalLineLoad(Line location, Loadcase loadcase, Vector force, string name = "")
        {
            return new GeometricalLineLoad
            {
                Location = location,
                Loadcase = loadcase,
                ForceA = force,
                ForceB = force,
                Name = name
            };
        }

        /***************************************************/
        /**** Public Methods - ToBeRemoved               ****/
        /***************************************************/

        [PreviousVersion("5.1", "BH.Engine.Adapters.Robot.Create.GeometricalLineLoad(BH.oM.Geometry.Line, BH.oM.Structure.Loads.Loadcase, BH.oM.Geometry.Vector, BH.oM.Geometry.Vector, BH.oM.Geometry.Vector, BH.oM.Geometry.Vector, System.String)")]
        [ToBeRemoved("3.1", "Replaced with autogenerated Property assignement method.")]
        public static GeometricalLineLoad GeometricalLineLoad(Line location, Loadcase loadcase, Vector forceAtStart, Vector forceAtEnd, Vector momentAtStart, Vector momentAtEnd, string name = "")
        {
            return new GeometricalLineLoad
            {
                Location = location,
                Loadcase = loadcase,
                ForceA = forceAtStart,
                ForceB = forceAtEnd,
                MomentA = momentAtStart,
                MomentB = momentAtEnd,
                Name = name
            };
        }

        /***************************************************/
    }
}




