using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

namespace BH.Engine.Reflection
{
    public static partial class Query
    {
        /***************************************************/
        /**** Public Methods                            ****/
        /***************************************************/

        public static List<MethodInfo> BHoMMethodList()
        {
            // If the dictionary exists already return it
            if (m_BHoMMethodList != null && m_BHoMMethodList.Count > 0)
                return m_BHoMMethodList;

            // Otherwise, create it
            ExtractAllMethods();

            return m_BHoMMethodList;
        }

        /***************************************************/

        public static List<MethodBase> AllMethodList()
        {
            // If the dictionary exists already return it
            if (m_AllMethodList != null && m_AllMethodList.Count > 0)
                return m_AllMethodList;

            // Otherwise, create it
            ExtractAllMethods();

            return m_AllMethodList;
        }


        /***************************************************/
        /**** Private Methods                           ****/
        /***************************************************/

        private static void ExtractAllMethods()
        {
            m_BHoMMethodList = new List<MethodInfo>();
            m_AllMethodList = new List<MethodBase>();

            BindingFlags bindingBHoM = BindingFlags.Public | BindingFlags.DeclaredOnly | BindingFlags.Static;

            foreach (Assembly asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    // Save BHoM objects only
                    string name = asm.GetName().Name;
                    if (name.EndsWith("_Engine"))
                    {
                        foreach (Type type in asm.GetTypes())
                        {
                            // Get only the BHoM methods
                            if (!type.IsInterface && type.IsAbstract)
                            {
                                MethodInfo[] typeMethods = type.GetMethods(bindingBHoM);
                                m_BHoMMethodList.AddRange(typeMethods.Where(x => x.IsLegal()));
                            }

                            // Get everything
                            StoreAllMethods(type);
                        }
                    }
                    else if (name.EndsWith("oM") || name.EndsWith("_Adapter") || name.EndsWith("_UI") || name.EndsWith("_Test"))
                    {
                        foreach (Type type in asm.GetTypes())
                        {
                            StoreAllMethods(type);
                        }
                    }
                }
                catch (Exception)
                {
                    Compute.RecordWarning("Cannot load types from assembly " + asm.GetName().Name);
                }
            }
        }

        /***************************************************/

        private static void StoreAllMethods(Type type)
        {
            BindingFlags bindingAll = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Instance;

            if (type.Namespace.StartsWith("BH.") && !type.IsAutoGenerated())
            {
                m_AllMethodList.AddRange(type.GetMethods(bindingAll).Where(x => x.GetMethodBody() != null && !x.IsAutoGenerated()));
                m_AllMethodList.AddRange(type.GetConstructors(bindingAll).Where(x => x.GetMethodBody() != null && !x.IsAutoGenerated()));
            }
        }

        /***************************************************/
        /**** Private Fields                            ****/
        /***************************************************/

        private static List<MethodInfo> m_BHoMMethodList = new List<MethodInfo>();
        private static List<MethodBase> m_AllMethodList = new List<MethodBase>();

        /***************************************************/
    }
}
